# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import gym_env_pb2 as gym__env__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gym_env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnvStub(object):
    """定义环境服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnvInteraction = channel.stream_stream(
                '/gym_env.Env/EnvInteraction',
                request_serializer=gym__env__pb2.EnvMessage.SerializeToString,
                response_deserializer=gym__env__pb2.EnvMessage.FromString,
                _registered_method=True)
        self.TrainingEnv = channel.unary_unary(
                '/gym_env.Env/TrainingEnv',
                request_serializer=gym__env__pb2.TrainingEnvRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestStepAction = channel.unary_unary(
                '/gym_env.Env/RequestStepAction',
                request_serializer=gym__env__pb2.ModelPredictActionRequest.SerializeToString,
                response_deserializer=gym__env__pb2.Step.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/gym_env.Env/Close',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class EnvServicer(object):
    """定义环境服务
    """

    def EnvInteraction(self, request_iterator, context):
        """用于双向流通信，支持服务端主动发起 Reset、Step，客户端响应一次
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainingEnv(self, request, context):
        """重置环境请求
        rpc Reset (google.protobuf.Empty) returns (stream ResetResponse) {}
        发送动作
        rpc StepAction (Step) returns (StepResult) {}
        请求训练模型
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestStepAction(self, request, context):
        """请求动作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """关闭环境通知
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnvInteraction': grpc.stream_stream_rpc_method_handler(
                    servicer.EnvInteraction,
                    request_deserializer=gym__env__pb2.EnvMessage.FromString,
                    response_serializer=gym__env__pb2.EnvMessage.SerializeToString,
            ),
            'TrainingEnv': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainingEnv,
                    request_deserializer=gym__env__pb2.TrainingEnvRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestStepAction': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestStepAction,
                    request_deserializer=gym__env__pb2.ModelPredictActionRequest.FromString,
                    response_serializer=gym__env__pb2.Step.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gym_env.Env', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gym_env.Env', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Env(object):
    """定义环境服务
    """

    @staticmethod
    def EnvInteraction(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gym_env.Env/EnvInteraction',
            gym__env__pb2.EnvMessage.SerializeToString,
            gym__env__pb2.EnvMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainingEnv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gym_env.Env/TrainingEnv',
            gym__env__pb2.TrainingEnvRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestStepAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gym_env.Env/RequestStepAction',
            gym__env__pb2.ModelPredictActionRequest.SerializeToString,
            gym__env__pb2.Step.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gym_env.Env/Close',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
